apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd-worker
spec:
  selector:
    matchLabels:
      app: nfd-worker
  template:
    metadata:
      labels:
        app: nfd-worker
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nfd-worker
          image: k8s.gcr.io/nfd/node-feature-discovery:v0.10.1
          imagePullPolicy: IfNotPresent
          command:
            - "nfd-worker"
          args:
            - "-server=nfd-master:8080"
