apiVersion: v1
entries:
  node-feature-discovery:
  - apiVersion: v2
    appVersion: v0.10.0
    created: "2022-01-11T19:09:04.218827373Z"
    description: 'Detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels. '
    digest: a1fc3e7532bf71e56a4b3e83a8f9a5e75688c86c14bfdf896e7b1c9b2003c744
    home: https://github.com/kubernetes-sigs/node-feature-discovery
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/kubernetes-sigs/node-feature-discovery
    type: application
    urls:
    - https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.10.0/node-feature-discovery-chart-0.10.0.tgz
    version: 0.10.0
  - apiVersion: v2
    appVersion: v0.9.0
    created: "2021-08-20T11:44:00.52567963Z"
    description: 'Detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels. '
    digest: 550d323bdac39f76537297df33bdfb32d4a81a0cf633e12c57cbec69e2ea24a7
    home: https://github.com/kubernetes-sigs/node-feature-discovery
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/kubernetes-sigs/node-feature-discovery
    type: application
    urls:
    - https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.9.0/node-feature-discovery-chart-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: v0.8.2
    created: "2021-05-18T18:36:57.203078072Z"
    description: 'Detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels. '
    digest: 9a8b7f8b0c12a891f6dd829b07c5a39ce7b783fccdcf76c8b57caf8ba53f4b0b
    home: https://github.com/kubernetes-sigs/node-feature-discovery
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/kubernetes-sigs/node-feature-discovery
    type: application
    urls:
    - https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.8.2/node-feature-discovery-chart-0.8.2.tgz
    version: 0.8.2
  - apiVersion: v2
    appVersion: v0.8.1
    created: "2021-04-06T15:07:12.708223702Z"
    description: 'Detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels. '
    digest: 0042668a6bf511e8dbde703a8373e0b20108e922fc81d54f090153c8ff9251df
    home: https://github.com/kubernetes-sigs/node-feature-discovery
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/kubernetes-sigs/node-feature-discovery
    type: application
    urls:
    - https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.8.1/node-feature-discovery-chart-0.8.1.tgz
    version: 0.8.1
  - apiVersion: v2
    appVersion: v0.8.0
    created: "2021-03-18T14:25:40.598963046Z"
    description: 'Detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels. '
    digest: fc71711ef3b46a24d3c229c72b6fa983b37629a3865c61bcf9e23ba3e39f67ff
    home: https://github.com/kubernetes-sigs/node-feature-discovery
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/kubernetes-sigs/node-feature-discovery
    type: application
    urls:
    - https://github.com/kubernetes-sigs/node-feature-discovery/releases/download/v0.8.0/node-feature-discovery-chart-0.8.0.tgz
    version: 0.8.0
generated: "2022-01-11T19:09:04.217237255Z"
