apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfd
  name: nfd-topology-gc
spec:
  selector:
    matchLabels:
      app: nfd-topology-gc
  template:
    metadata:
      labels:
        app: nfd-topology-gc
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: nfd-topology-gc
      containers:
        - name: nfd-topology-gc
          image: registry.k8s.io/nfd/node-feature-discovery:v0.13.2
          imagePullPolicy: IfNotPresent
          command:
            - "nfd-topology-gc"
